import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      collapsed: false,
      link: {
        type: 'generated-index',
        description: 'Learn about ROS 2 fundamentals for robotics'
      },
      items: [
        {type: 'autogenerated', dirName: '01-ros2-basics'}
      ]
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      collapsed: false,
      link: {
        type: 'generated-index',
        description: 'Learn about digital twins using Gazebo and Unity for robotics simulation'
      },
      items: [
        {type: 'autogenerated', dirName: '02-digital-twin'}
      ]
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac™)',
      collapsed: false,
      link: {
        type: 'generated-index',
        description: 'Learn about NVIDIA Isaac tools for robot perception, SLAM, mapping, and navigation'
      },
      items: [
        {type: 'autogenerated', dirName: '03-ai-robot-brain'}
      ]
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA) Robotics',
      collapsed: false,
      link: {
        type: 'generated-index',
        description: 'Learn about VLA robotics combining vision, language, and action for humanoid robots'
      },
      items: [
        {type: 'autogenerated', dirName: '04-vla-robotics'}
      ]
    }
  ]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
